# Generated by Django 2.2.7 on 2019-11-26 14:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('data_criacao', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('titulacao', models.CharField(default='titular', max_length=50)),
                ('endereço', models.CharField(default='0', max_length=50)),
                ('telefone', models.CharField(default='0', max_length=30)),
                ('disciplina', models.ManyToManyField(to='sistema.Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('matrícula', models.CharField(default='0', max_length=50)),
                ('nota', models.CharField(default='0', max_length=50)),
                ('faltas', models.CharField(default='0', max_length=50)),
                ('disciplinas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Disciplina')),
            ],
        ),
    ]
