# Generated by Django 2.2.7 on 2019-11-26 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='disciplinas',
        ),
    ]
