# Generated by Django 2.2.1 on 2019-06-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='faltas',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='aluno',
            name='nota',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
