# Generated by Django 2.2.2 on 2019-11-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_remove_aluno_disciplinas'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='ano_letivo',
            field=models.IntegerField(default='2019', max_length=4),
        ),
        migrations.AlterField(
            model_name='professor',
            name='endereço',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='professor',
            name='telefone',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(blank=True, default=2019)),
                ('disciplina', models.ManyToManyField(to='sistema.Disciplina')),
            ],
        ),
    ]
