# Generated by Django 2.2.1 on 2019-06-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_auto_20190602_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='matrícula',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='professor',
            name='endereço',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='professor',
            name='telefone',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
