# Generated by Django 2.2.2 on 2019-11-27 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_auto_20191126_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='aluno',
            field=models.OneToOneField(default='nome', on_delete=django.db.models.deletion.CASCADE, to='sistema.Aluno'),
        ),
    ]
