# Generated by Django 2.2.2 on 2019-11-27 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_auto_20191126_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='aluno',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='sistema.Aluno'),
        ),
    ]
