# Generated by Django 2.2.7 on 2019-11-29 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_auto_20191126_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='ano_letivo',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='faltas',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='nota',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='data_criacao',
        ),
        migrations.AddField(
            model_name='matricula',
            name='ano',
            field=models.IntegerField(default='2019'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='faltas',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='matricula',
            name='nota',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Aluno'),
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='disciplina',
        ),
        migrations.AddField(
            model_name='matricula',
            name='disciplina',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sistema.Disciplina'),
        ),
        migrations.CreateModel(
            name='Alocacao',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('ano', models.CharField(max_length=4)),
                ('carga', models.IntegerField()),
                ('horario', models.TimeField()),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Professor')),
            ],
            options={
                'verbose_name_plural': 'Alocações',
            },
        ),
    ]
