# Generated by Django 2.2.7 on 2019-11-29 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_auto_20191129_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='disciplina',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sistema.Disciplina'),
        ),
    ]
